#! /bin/sh

# Hotplug Dual Monitors
INTERNAL_MONITOR="eDP-1-1"
EXTERNAL_MONITOR="HDMI-0"
# Default Workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$INTERNAL_MONITOR" -d I II III IV V
    bspc monitor "$EXTERNAL_MONITOR" -d VI VII VIII IX X
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
  else
    bspc monitor -d I II III IV V VI VII VIII IX X
  fi
fi
monitor_add() {
  # Move last 5 desktops to external monitor
  for desktop in $(bspc query -D --names -m "$EXTERNAL_MONITOR" | sed 5q); do
    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
  done

  # Remove default desktop created by bspwm
  bspc desktop Desktop --remove

  # Keep Internal as Primary, External as Secondary
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
}
monitor_remove() {
  # Add default temp desktop because a minimum of one desktop is required per monitor
  bspc monitor "$EXTERNAL_MONITOR" -a Desktop

  # Move all desktops except the last default desktop to internal monitor
  for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR");	do
    bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
  done

  # delete default desktops
  bspc desktop Desktop --remove

  # reorder desktops
  bspc monitor "$INTERNAL_MONITOR" -o I II III IV V VI VII VIII IX X
}

bspc config border_width          2
bspc config window_gap            4
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Border Colors
bspc config focused_border_color "#1b1f20"
bspc config presel_feedback_color "#d8b4bd"
bspc config top_padding 30

# Define Rule 
bspc rule -a discord desktop='IV' follow=off
bspc rule -a Zathura state=tiled

# Background
feh --bg-fill ~/Pictures/Wallpapers/opal.webp --bg-fill  ~/Pictures/Wallpapers/opal.webp

# Fix Intellij
export AWT_TOOLKIT=MToolkit
wmname compiz


# Auto start stuff
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  # Set xrandr for multi monitor
  xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --primary --rotate normal --output "$EXTERNAL_MONITOR" --mode 1920x1080 --rotate normal --right-of "$INTERNAL_MONITOR"
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
    monitor_add
  fi
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
  # set xrandr rules for laptop only
  xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
    monitor_remove
  fi
fi
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
dunst ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
