#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Border Colors
bspc config focused_border_color "#1b1f20"
bspc config presel_feedback_color "#d8b4bd"
bspc config top_padding 40

# Define Rule 
bspc rule -a discord desktop='IV' follow=off
bspc rule -a Zathura state=tiled

#Background
feh --bg-fill ~/Downloads/Wallpapers/opal.webp

#Fix Intellij
export AWT_TOOLKIT=MToolkit
wmname compiz

# Auto start stuff
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --experimental-backends &
dunst ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &
